export const AXIOS_POST = 'AXIOS_POST';
export const AXIOS_POST_REQUEST = 'AXIOS_POST_REQUEST';
export const AXIOS_POST_SUCCESS = 'AXIOS_POST_SUCCESS';
export const AXIOS_POST_FAILURE = 'AXIOS_POST_FAILURE';
